# Generated by Django 6.0.1 on 2026-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
