# Generated by Django 6.0.1 on 2026-01-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='driver',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='fuel_cost',
            new_name='revenue',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('TOLL', 'Toll'), ('FOOD', 'Food'), ('MAINTENANCE', 'Maintenance'), ('INSURANCE', 'Insurance'), ('EMI', 'EMI'), ('SALARY', 'Salary'), ('REPAIR', 'Repair'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.truck'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip'),
        ),
    ]
